name: Code Rabbit AI PR Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, ready_for_review]

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}-${{ github.event_name == 'pull_request' && 'pr_event' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          openai_model: gpt-4o-mini
          language: ja-JP
          system_message: |
            あなたは経験豊富なソフトウェアエンジニアとして、次のガイドラインに従ってPRをレビューしてください：
            - すべてレビューに関しては日本語で回答すること
            - コードの問題点は具体的な改善案と共に指摘すること
            - セキュリティ上の懸念がある場合は特に詳しく説明すること
            - コードの改善案は具体的なコードと共に指摘すること
            - 必要に応じて代替可能なライブラリやツールを提案すること
          summarize: |
            次のmarkdownフォーマット形式を使用して、本PRの要約を出力します。

            [出力形式]
            ## 要約
            <!-- 特定のファイルではなく、全体の変更に関する高レベルの要約を80語以内で。 -->
            ## 変更点
            <!-- ファイルとその要約のテーブル。スペースを節約するために、同様の変更を持つファイルを1行にまとめることができます。 -->
